myservice:
  greeting: "Dev-envirnoment::::config server of application properties & activated profile is dev environment!"
  
        
eureka:
   client:
      register-with-eureka: true
      fetch-registry: true
      service-url: 
         default-zone: http://localhost:8761/eureka/
      instance:
          hostname: localhost
