myservice:
  greeting: "Hello from the Config Server dev environment profile!"
  
        
eureka:
   client:
      register-with-eureka: true
      fetch-registry: true
      service-url: 
         default-zone: http://localhost:8761/eureka/
      instance:
          hostname: localhost
