myservice:
  greeting: "Activated profie is ::: DEV from config server, application-dev.yml!!!!!!!!"
  
        
eureka:
   client:
      register-with-eureka: true
      fetch-registry: true
      service-url: 
         default-zone: http://localhost:8761/eureka/
      instance:
          hostname: localhost
